import pandas as pd
import numpy as np
from scipy.stats import pearsonr
import os
import sys
import xgboost as xgb
import lightgbm as lgb
import catboost as cb
sys.path.insert(0, os.path.dirname(__file__))

def finalize():
    print("======================================================================")
    print("  FINALIZING ROBUST IMPROVEMENTS: MERGING CATALOGS & PLOTS")
    print("======================================================================")
    
    # 1. Load the new reliability catalog generated by run_robust_improvements.py
    rel_cat = pd.read_csv("data/DR3_New_AGN_Redshift_Catalog_Reliability.csv")
    rel_cat['Source_Name'] = rel_cat['Source_Name'].astype(str).str.strip()
    
    # Load the base model predictions from target_df (which was saved or we can compute)
    # Let's read the saved intermediate output or run a quick prediction merge
    # In run_robust_improvements.py, we have the final model prediction on target_df
    # We can reconstruct it from the run_robust_improvements results
    
    # Load old catalog to preserve neural model predictions (ft_z, tabnet_z, tabm_z, saint_z)
    old_cat = pd.read_csv("data/DR3_New_AGN_Redshift_Catalog_Improved.csv")
    old_cat['Source_Name'] = old_cat['Source_Name'].astype(str).str.strip()
    
    # Let's read target_df from running prediction again, or let's use the run_robust_improvements logic.
    # To do it cleanly, let's run the model inference and build the updated dataframe.
    # We will import the necessary parts or load the raw data.
    
    print("Merging new predictions into DR3_New_AGN_Redshift_Catalog_Improved.csv...")
    
    # Let's perform the prediction inside this script to ensure we get the exact xgb, lgb, cat, tabpfn predictions
    train_raw = pd.read_csv("data/training_eligible.csv")
    mw = pd.read_csv("data/multi_wavelength_matches.csv")
    mw['Source_Name'] = mw['Source_Name'].astype(str).str.strip()
    train_df = pd.merge(train_raw, mw, on="Source_Name", how="left")
    
    # Load target
    from astropy.io import fits
    with fits.open("data/table-4LAC-DR3-h.fits") as h_hdul:
        df_h = pd.DataFrame(h_hdul[1].data)
    with fits.open("data/table-4LAC-DR3-l.fits") as df_l:
        df_l = pd.DataFrame(df_l[1].data)
    dr3 = pd.concat([df_h, df_l], ignore_index=True)
    for col in dr3.columns:
        if dr3[col].dtype == object:
            dr3[col] = dr3[col].astype(str).str.strip()
    dr3['Source_Name'] = dr3['Source_Name'].astype(str).str.strip()
            
    dr2 = pd.read_csv("data/4LAC-DR2.csv")
    dr2_names = set(dr2['Source_Name'].astype(str).str.strip())
    new_names = set(dr3['Source_Name']) - dr2_names
    target_df = dr3[dr3['Source_Name'].isin(new_names)].copy()
    
    gaia_new = pd.read_csv("data/gaia_magnitudes_dr3_new.csv")
    gaia_new['Source_Name'] = gaia_new['Source_Name'].astype(str).str.strip()
    target_df = pd.merge(target_df, gaia_new, on="Source_Name", how="left")
    target_df = pd.merge(target_df, mw, on="Source_Name", how="left")
    
    # Numeric preprocessing
    name_map = {
        'Flux1000': 'LogFlux',
        'Energy_Flux100': 'LogEnergy_Flux',
        'Signif_Avg': 'LogSignificance',
        'Variability_Index': 'LogVariability_Index',
        'nu_syn': 'Lognu_syn',
        'nuFnu_syn': 'LognuFnu_syn',
        'Pivot_Energy': 'LogPivot_Energy'
    }
    
    for df in [train_df, target_df]:
        df['PL_Index'] = pd.to_numeric(df['PL_Index'], errors='coerce')
        df['LP_Index'] = pd.to_numeric(df['LP_Index'], errors='coerce')
        df['LP_beta'] = pd.to_numeric(df['LP_beta'], errors='coerce')
        df['Gaia_G_Magnitude'] = pd.to_numeric(df['Gaia_G_Magnitude'], errors='coerce')
        for raw_col, log_col in name_map.items():
            val = pd.to_numeric(df[raw_col], errors='coerce')
            val = np.where(val > 0, val, np.nan)
            df[log_col] = np.log10(val)
        df['Redshift'] = pd.to_numeric(df['Redshift'], errors='coerce')
        df['InvRedshift'] = 1.0 / (1.0 + df['Redshift'])
        df['W1mag'] = pd.to_numeric(df['W1mag'], errors='coerce')
        df['W2mag'] = pd.to_numeric(df['W2mag'], errors='coerce')
        df['W3mag'] = pd.to_numeric(df['W3mag'], errors='coerce')
        df['W4mag'] = pd.to_numeric(df['W4mag'], errors='coerce')
        df['S1.4'] = pd.to_numeric(df['S1.4'], errors='coerce')
        df['CR0'] = pd.to_numeric(df['CR0'], errors='coerce')
        df['Is_Upper_Limit_Xray'] = df['CR0'].isna().astype(float)
        df['LogXrayFlux'] = np.where(df['CR0'].isna(), -4.0, np.log10(df['CR0'].clip(lower=1e-6)))
        df['LogRadioFlux'] = np.log10(df['S1.4'].clip(lower=1e-5))

    orig_features = ["LogFlux", "LogEnergy_Flux", "LogSignificance", "LogVariability_Index",
                     "Lognu_syn", "LognuFnu_syn", "PL_Index", "LogPivot_Energy", "LP_Index",
                     "LP_beta", "Gaia_G_Magnitude"]
    impute_features = orig_features + ["W1mag", "W2mag", "W3mag", "W4mag", "LogRadioFlux"]
    
    from sklearn.experimental import enable_iterative_imputer
    from sklearn.impute import IterativeImputer
    imputer = IterativeImputer(max_iter=15, random_state=42)
    train_df[impute_features] = imputer.fit_transform(train_df[impute_features])
    target_df[impute_features] = imputer.transform(target_df[impute_features])
    
    for df in [train_df, target_df]:
        df['W1_W2'] = df['W1mag'] - df['W2mag']
        df['W2_W3'] = df['W2mag'] - df['W3mag']
        df['W3_W4'] = df['W3mag'] - df['W4mag']
        df['RadioLoudness'] = df['LogRadioFlux'] - df['LogFlux']
        df['XrayToOptical'] = df['LogXrayFlux'] + 0.4 * df['Gaia_G_Magnitude']
        df['IRToRadio'] = -0.4 * df['W1mag'] - df['LogRadioFlux']
        df['IndexDiff'] = df['PL_Index'] - df['LP_Index']
        
    predictors = orig_features + ["W1mag", "W2mag", "W3mag", "W4mag", "W1_W2", "W2_W3", "W3_W4",
                                  "LogRadioFlux", "LogXrayFlux", "RadioLoudness", "XrayToOptical",
                                  "IRToRadio", "IndexDiff", "Is_Upper_Limit_Xray"]
    
    # Class probability P_FSRQ
    from sklearn.ensemble import RandomForestClassifier
    from sklearn.model_selection import StratifiedKFold
    skf = StratifiedKFold(n_splits=10, shuffle=True, random_state=42)
    train_probs = np.zeros(len(train_df))
    X_train_class = train_df[predictors]
    y_train_class = train_df['LabelNo'].fillna(0).astype(int).values
    X_target_class = target_df[predictors]
    
    for train_idx, val_idx in skf.split(X_train_class, y_train_class):
        clf = RandomForestClassifier(n_estimators=300, max_depth=6, random_state=42, n_jobs=-1)
        clf.fit(X_train_class.iloc[train_idx], y_train_class[train_idx])
        train_probs[val_idx] = clf.predict_proba(X_train_class.iloc[val_idx])[:, 1]
        
    final_clf = RandomForestClassifier(n_estimators=300, max_depth=6, random_state=42, n_jobs=-1)
    final_clf.fit(X_train_class, y_train_class)
    target_df['P_FSRQ'] = final_clf.predict_proba(X_target_class)[:, 1]
    train_df['P_FSRQ'] = train_probs
    
    predictors = predictors + ['P_FSRQ']
    
    # DRIW weights
    from sklearn.linear_model import LogisticRegression
    X_all = np.vstack([train_df[predictors].values, target_df[predictors].values])
    y_domain = np.hstack([np.zeros(len(train_df)), np.ones(len(target_df))])
    domain_clf = LogisticRegression(C=0.1, random_state=42)
    domain_clf.fit(X_all, y_domain)
    p_target_train = domain_clf.predict_proba(train_df[predictors].values)[:, 1]
    weights = p_target_train / (1.0 - p_target_train + 1e-6)
    weights = np.clip(weights, 0.05, 5.0)
    
    # Target transformation (QuantileTransformer)
    from sklearn.preprocessing import QuantileTransformer, StandardScaler
    y_train = train_df['InvRedshift'].values
    qt = QuantileTransformer(n_quantiles=100, output_distribution='normal', random_state=42)
    y_train_trans = qt.fit_transform(y_train.reshape(-1, 1)).flatten()
    
    # Stacking level 0 CV
    from sklearn.model_selection import KFold
    cv = KFold(n_splits=5, shuffle=True, random_state=42)
    X = train_df[predictors].values
    X_target = target_df[predictors].values
    scaler = StandardScaler()
    X_sc = scaler.fit_transform(X)
    X_target_sc = scaler.transform(X_target)
    
    xgb_reg = xgb.XGBRegressor(n_estimators=300, learning_rate=0.04, max_depth=4, subsample=0.8, colsample_bytree=0.8, random_state=42, n_jobs=-1)
    lgb_reg = lgb.LGBMRegressor(n_estimators=300, learning_rate=0.04, max_depth=4, num_leaves=15, subsample=0.8, colsample_bytree=0.8, random_state=42, n_jobs=-1, verbose=-1)
    cat_reg = cb.CatBoostRegressor(iterations=300, learning_rate=0.04, depth=4, random_seed=42, thread_count=-1, verbose=0)
    from tabpfn import TabPFNRegressor
    tabpfn_reg = TabPFNRegressor(random_state=42, ignore_pretraining_limits=True)
    
    oof_preds_trans = {'xgb': np.zeros(len(train_df)), 'lgb': np.zeros(len(train_df)), 'cat': np.zeros(len(train_df)), 'tabpfn': np.zeros(len(train_df))}
    
    for train_idx, val_idx in cv.split(X):
        w_fold = weights[train_idx]
        xgb_reg.fit(X[train_idx], y_train_trans[train_idx], sample_weight=w_fold)
        lgb_reg.fit(X[train_idx], y_train_trans[train_idx], sample_weight=w_fold)
        cat_reg.fit(X[train_idx], y_train_trans[train_idx], sample_weight=w_fold)
        
        X_tr_sc = scaler.fit_transform(X[train_idx])
        X_va_sc = scaler.transform(X[val_idx])
        tabpfn_reg.fit(X_tr_sc, y_train_trans[train_idx])
        
        oof_preds_trans['xgb'][val_idx] = xgb_reg.predict(X[val_idx])
        oof_preds_trans['lgb'][val_idx] = lgb_reg.predict(X[val_idx])
        oof_preds_trans['cat'][val_idx] = cat_reg.predict(X[val_idx])
        oof_preds_trans['tabpfn'][val_idx] = tabpfn_reg.predict(X_va_sc)
        
    oof_preds_inv = {}
    for key in oof_preds_trans.keys():
        oof_preds_inv[key] = qt.inverse_transform(oof_preds_trans[key].reshape(-1, 1)).flatten()
        
    # NNLS Stacking Meta-Learner
    from sklearn.linear_model import LinearRegression
    X_level1 = np.column_stack([oof_preds_inv['xgb'], oof_preds_inv['lgb'], oof_preds_inv['cat'], oof_preds_inv['tabpfn']])
    meta_model = LinearRegression(positive=True)
    meta_model.fit(X_level1, y_train)
    
    # Train final models
    xgb_reg.fit(X, y_train_trans, sample_weight=weights)
    lgb_reg.fit(X, y_train_trans, sample_weight=weights)
    cat_reg.fit(X, y_train_trans, sample_weight=weights)
    tabpfn_reg.fit(X_sc, y_train_trans)
    
    pred_trans = {
        'xgb': xgb_reg.predict(X_target),
        'lgb': lgb_reg.predict(X_target),
        'cat': cat_reg.predict(X_target),
        'tabpfn': tabpfn_reg.predict(X_target_sc)
    }
    
    pred_inv = {}
    for key in pred_trans.keys():
        pred_inv[key] = qt.inverse_transform(pred_trans[key].reshape(-1, 1)).flatten()
        
    X_level1_target = np.column_stack([pred_inv['xgb'], pred_inv['lgb'], pred_inv['cat'], pred_inv['tabpfn']])
    pred_stack_inv = meta_model.predict(X_level1_target)
    
    # Calibrate
    oof_stack_inv = meta_model.predict(X_level1)
    from sklearn.isotonic import IsotonicRegression
    bll_mask = (train_df['LabelNo'].values == 0)
    fsrq_mask = (train_df['LabelNo'].values == 1)
    iso_bll = IsotonicRegression(out_of_bounds='clip').fit(oof_stack_inv[bll_mask], y_train[bll_mask])
    iso_fsrq = IsotonicRegression(out_of_bounds='clip').fit(oof_stack_inv[fsrq_mask], y_train[fsrq_mask])
    
    p_train = train_df['P_FSRQ'].values
    oof_corr_inv = (1.0 - p_train) * iso_bll.predict(oof_stack_inv) + p_train * iso_fsrq.predict(oof_stack_inv)
    oof_ensemble_z = (1.0 / oof_corr_inv) - 1.0
    
    p_target = target_df['P_FSRQ'].values
    new_corr_inv = (1.0 - p_target) * iso_bll.predict(pred_stack_inv) + p_target * iso_fsrq.predict(pred_stack_inv)
    ensemble_z = (1.0 / new_corr_inv) - 1.0
    
    # Calculate std
    pred_inv_matrix = np.column_stack([pred_inv['xgb'], pred_inv['lgb'], pred_inv['cat'], pred_inv['tabpfn']])
    pred_z_matrix = 1.0 / pred_inv_matrix - 1.0
    std_z = np.std(pred_z_matrix, axis=1)
    
    oof_inv_matrix = np.column_stack([oof_preds_inv['xgb'], oof_preds_inv['lgb'], oof_preds_inv['cat'], oof_preds_inv['tabpfn']])
    oof_z_matrix = 1.0 / oof_inv_matrix - 1.0
    oof_std_z = np.std(oof_z_matrix, axis=1)
    
    # Conformal Prediction
    residuals_z = np.abs(train_df['Redshift'].values - oof_ensemble_z)
    oof_std_z_clipped = np.clip(oof_std_z, a_min=0.01, a_max=None)
    conformal_scores = residuals_z / oof_std_z_clipped
    q_68 = np.percentile(conformal_scores, 68.0)
    q_95 = np.percentile(conformal_scores, 95.0)
    
    z_low_68 = np.clip(ensemble_z - q_68 * std_z, a_min=0.0, a_max=None)
    z_high_68 = ensemble_z + q_68 * std_z
    z_low_95 = np.clip(ensemble_z - q_95 * std_z, a_min=0.0, a_max=None)
    z_high_95 = ensemble_z + q_95 * std_z
    
    confidence_score = np.exp(-std_z / (1 + ensemble_z))
    
    # Merge into old_cat structure
    print("Writing new values to DR3_New_AGN_Redshift_Catalog_Improved.csv...")
    for idx, row in target_df.iterrows():
        sname = row['Source_Name']
        # Find index in old_cat
        old_idx_list = old_cat[old_cat['Source_Name'] == sname].index
        if len(old_idx_list) > 0:
            old_idx = old_idx_list[0]
            # Get target index
            t_idx = target_df.index.get_loc(idx)
            
            # Update columns
            old_cat.loc[old_idx, 'p_fsrq'] = p_target[t_idx]
            old_cat.loc[old_idx, 'xgb_z'] = 1.0 / pred_inv['xgb'][t_idx] - 1.0
            old_cat.loc[old_idx, 'lgbm_z'] = 1.0 / pred_inv['lgb'][t_idx] - 1.0
            old_cat.loc[old_idx, 'catboost_z'] = 1.0 / pred_inv['cat'][t_idx] - 1.0
            old_cat.loc[old_idx, 'tabpfn_z'] = 1.0 / pred_inv['tabpfn'][t_idx] - 1.0
            old_cat.loc[old_idx, 'ensemble_z'] = ensemble_z[t_idx]
            old_cat.loc[old_idx, 'prediction_std'] = std_z[t_idx]
            old_cat.loc[old_idx, 'confidence_score'] = confidence_score[t_idx]
            old_cat.loc[old_idx, 'z_low_68'] = z_low_68[t_idx]
            old_cat.loc[old_idx, 'z_high_68'] = z_high_68[t_idx]
            old_cat.loc[old_idx, 'z_low_95'] = z_low_95[t_idx]
            old_cat.loc[old_idx, 'z_high_95'] = z_high_95[t_idx]
            
    old_cat.to_csv("data/DR3_New_AGN_Redshift_Catalog_Improved.csv", index=False)
    print("Catalog updated successfully!")
    
    # Calculate the test metrics on n=89
    spec_sources = target_df[target_df['Redshift'] > 0].copy()
    y_test_spec = spec_sources['Redshift'].values
    spec_names = set(spec_sources['Source_Name'])
    final_spec = old_cat[old_cat['Source_Name'].isin(spec_names)].copy()
    final_spec['order'] = final_spec['Source_Name'].map(lambda x: list(spec_sources['Source_Name']).index(x))
    final_spec = final_spec.sort_values('order')
    
    print(f"\n=== ROBUST METRICS ON SPECTROSCOPIC SUBSET (n={len(y_test_spec)}) ===")
    print(f"{'Model':<20} | {'Pearson R':<10} | {'RMSE':<8}")
    print("-" * 45)
    
    for m_key, m_name in [('xgb_z', 'XGBoost'), ('lgbm_z', 'LightGBM'), ('catboost_z', 'CatBoost'), 
                          ('ft_z', 'FT-Transformer'), ('tabpfn_z', 'TabPFN'), ('tabnet_z', 'TabNet'),
                          ('tabm_z', 'TabM'), ('saint_z', 'SAINT'), ('ensemble_z', 'Ensemble')]:
        preds = final_spec[m_key].values
        r_val, _ = pearsonr(preds, y_test_spec)
        rmse_val = np.sqrt(np.mean((preds - y_test_spec) ** 2))
        print(f"{m_name:<20} | {r_val:<10.4f} | {rmse_val:<8.4f}")
        
    # Run the plot generation
    print("\nRegenerating diagnostic plots...")
    import generate_improved_plots
    generate_improved_plots.generate_plots()
    
    print("\nCatalog and plots updated successfully!")

if __name__ == '__main__':
    finalize()
